-- Seed the global interests catalogue (idempotent).
INSERT INTO "interests" ("name", "category") VALUES
  ('Live Music', 'music'),
  ('Concerts', 'music'),
  ('Singing', 'music'),
  ('Guitar', 'music'),
  ('K-Pop', 'music'),
  ('Bollywood Music', 'music'),
  ('Indie Music', 'music'),
  ('Hip Hop', 'music'),
  ('Coffee', 'food & drink'),
  ('Foodie', 'food & drink'),
  ('Cooking', 'food & drink'),
  ('Baking', 'food & drink'),
  ('Street Food', 'food & drink'),
  ('Wine Tasting', 'food & drink'),
  ('Tea', 'food & drink'),
  ('Vegan Food', 'food & drink'),
  ('Hiking', 'outdoors'),
  ('Trekking', 'outdoors'),
  ('Camping', 'outdoors'),
  ('Nature', 'outdoors'),
  ('Beach Days', 'outdoors'),
  ('Road Trips', 'outdoors'),
  ('Cycling', 'outdoors'),
  ('Stargazing', 'outdoors'),
  ('Travel', 'travel'),
  ('Backpacking', 'travel'),
  ('Weekend Getaways', 'travel'),
  ('Mountains', 'travel'),
  ('Gym', 'fitness'),
  ('Running', 'fitness'),
  ('Yoga', 'fitness'),
  ('Meditation', 'fitness'),
  ('Swimming', 'fitness'),
  ('Dance', 'fitness'),
  ('Football', 'fitness'),
  ('Cricket', 'fitness'),
  ('Badminton', 'fitness'),
  ('Art', 'arts & culture'),
  ('Painting', 'arts & culture'),
  ('Photography', 'arts & culture'),
  ('Museums', 'arts & culture'),
  ('Theatre', 'arts & culture'),
  ('Writing', 'arts & culture'),
  ('Poetry', 'arts & culture'),
  ('Design', 'arts & culture'),
  ('Movies', 'entertainment'),
  ('Netflix', 'entertainment'),
  ('Anime', 'entertainment'),
  ('Stand-up Comedy', 'entertainment'),
  ('Board Games', 'entertainment'),
  ('Video Games', 'entertainment'),
  ('Puzzles', 'entertainment'),
  ('Chess', 'entertainment'),
  ('Reading', 'learning'),
  ('Books', 'learning'),
  ('Podcasts', 'learning'),
  ('Languages', 'learning'),
  ('Science', 'learning'),
  ('History', 'learning'),
  ('Fashion', 'lifestyle'),
  ('Thrifting', 'lifestyle'),
  ('Pets', 'lifestyle'),
  ('Dogs', 'lifestyle'),
  ('Cats', 'lifestyle'),
  ('Gardening', 'lifestyle'),
  ('Volunteering', 'lifestyle'),
  ('Spirituality', 'lifestyle'),
  ('Tech', 'tech'),
  ('Coding', 'tech'),
  ('Startups', 'tech'),
  ('Gadgets', 'tech'),
  ('AI', 'tech')
ON CONFLICT ("name") DO NOTHING;
